### ISSUE TITLE
creation of ld ref files

### ISSUE THREAD

**Issue by schavezchavez** [mulinlab/CAUSALdb-finemapping-pip#3]
Hi Jianhua,

First of all, thank you very much for the creation of this amazing tool.
I am trying to use it for finemapping of my own GWAS. I would like to use the genotype data i used to run the GWAS. I think is similar to 1KG data, but it would be better to use my own data. 
I was wondering if you have any suggestion on how to run Causaldb using my own data. I have vcf.gz and vcf.gz.tbi files per chromosome. Do you know then perhaps how to generate the requiered reference files from my own data?

thank you so much in advance.

Sergio

**Comment by Jianhua-Wang** [comment]
Our [ref/01_prepare_reference.py](https://github.com/mulinlab/CAUSALdb-finemapping-pip/blob/master/ref/01_prepare_reference.py) may not suit you if you are using a custom reference. 
And perhaps you need to perform fine-mapping on your own.
These are what I think may be helpful to you:
1. Make sure that your variants are all biallelic, MAF>0, and no duplicates. Otherwise, you would have problems when calculating LD. And the most important, each variant should have a unique ID.
2. Define regions of interest (using the [LD blocks](https://bitbucket.org/nygcresearch/ldetect-data/src/master/) or ±1Mb of every leading variant)
3. For each region of interest, extract the genotypes and summary statistics of the region and keep the overlapped variants, which are the variants you are going to fine-map.
4. For LD calculation, I recommend [`PLINK -r square spaces`](https://www.cog-genomics.org/plink/1.9/ld#r) which can take VCF as input directly.
5. For Fine-mapping tools, I recommend [FINEMAP](http://www.christianbenner.com) for speed and ease of use. It outputs 95% credible sets by default.

**Comment by schavezchavez** [comment]
Dear Jianhua,

Thank you very much for your reply. I will give it a try like this then.

Kind regards,

Sergio
