### ISSUE TITLE
Question about summary stats format

### ISSUE THREAD

**Issue by montenegrina** [mulinlab/CAUSALdb-finemapping-pip#5]
Hello,

I have summary statistics in this format (output from METAL software)

SNP BP CHR A1 A2 Weight Z P Direction
rs11693919 127673527 2 C T 19586 -5.565 2.617e-08 ---
rs10203679 127672359 2 C T 19586 -5.536 3.089e-08 ---

I see that your format requires BETA and SE. Can you please tell me how can I calculate those from the data I have?

Also does fine-mapping performed here has anything to do with the fact that for CasualDB variant allele frequency was derived from gnomAD?

Thanks
Ana

**Comment by Jianhua-Wang** [comment]
You can't calculate BETA and SE from P-value and Zscore. But I remember that METAL can output BETA and SE, try to read the documentation of METAL and find out.

Fine-mapping approaches in CAUSALdb have nothing to do with the allele frequency derived from gnomAD, we use the allele frequency in the original data source, if it's avaliable. Otherwise, the allele frequency of the corresponding population in 1000G Project was used.
